[book]
authors = ["Nameson Gaudel"]
language = "en"
multilingual = true
src = "src"

[output.html]
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/nameson2672/notebook"
edit-url-template = "https://github.com/nameson2672/notebook"