name: CICD

on:
  push:
    branch:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: HEROKU_API_KEY

    # Use Checkout action to copy file and change diractory to the app location
    steps:
    - uses: actions/checkout@v1
    
    # Push to heroku
    - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.APP_NAME }}