name: CICD

on:
  push:
    branch:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'dotnet-docker-heroku-app' }}

jobs:
  build:
    runs-on: ubuntu-latest

    # Use Checkout action to copy file and change diractory to the app location
    steps:
    - uses: actions/checkout@v1
    
    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME